//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Diploma_Project {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class kz_local {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal kz_local() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Diploma_Project.kz_local", typeof(kz_local).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Kosymsha.
        /// </summary>
        internal static string Additionally {
            get {
                return ResourceManager.GetString("Additionally", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Barlygy.
        /// </summary>
        internal static string All {
            get {
                return ResourceManager.GetString("All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Iterasialyq kiltter massıvi.
        /// </summary>
        internal static string Array_of_iterative_keys {
            get {
                return ResourceManager.GetString("Array of iterative keys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на бит.
        /// </summary>
        internal static string Bit {
            get {
                return ResourceManager.GetString("Bit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Baittar tizbegi.
        /// </summary>
        internal static string Byte_sequence {
            get {
                return ResourceManager.GetString("Byte sequence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Tandau.
        /// </summary>
        internal static string Choose {
            get {
                return ResourceManager.GetString("Choose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Tandaldy.
        /// </summary>
        internal static string Choosed {
            get {
                return ResourceManager.GetString("Choosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Kirilisa.
        /// </summary>
        internal static string Cyrillic {
            get {
                return ResourceManager.GetString("Cyrillic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на D.
        /// </summary>
        internal static string D {
            get {
                return ResourceManager.GetString("D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Desifrleu.
        /// </summary>
        internal static string Decrypt {
            get {
                return ResourceManager.GetString("Decrypt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Desifrleu.
        /// </summary>
        internal static string Decryption {
            get {
                return ResourceManager.GetString("Decryption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на S.
        /// </summary>
        internal static string E {
            get {
                return ResourceManager.GetString("E", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Sifrleu.
        /// </summary>
        internal static string Encrypt {
            get {
                return ResourceManager.GetString("Encrypt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Sifrlengen matin.
        /// </summary>
        internal static string Encrypted_Text {
            get {
                return ResourceManager.GetString("Encrypted Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Sifrleu.
        /// </summary>
        internal static string Encryption {
            get {
                return ResourceManager.GetString("Encryption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Kiltti engiziniz.
        /// </summary>
        internal static string Enter_the_key {
            get {
                return ResourceManager.GetString("Enter the key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Sifrlenetin matindi engiziniz.
        /// </summary>
        internal static string Enter_the_text_to_encrypt_decrypt {
            get {
                return ResourceManager.GetString("Enter the text to encrypt/decrypt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на G.
        /// </summary>
        internal static string G {
            get {
                return ResourceManager.GetString("G", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Jasau.
        /// </summary>
        internal static string Generate {
            get {
                return ResourceManager.GetString("Generate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на GOST 34-12.
        /// </summary>
        internal static string GOST_34_12 {
            get {
                return ResourceManager.GetString("GOST 34-12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Kilt.
        /// </summary>
        internal static string Key {
            get {
                return ResourceManager.GetString("Key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Til.
        /// </summary>
        internal static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Latyn.
        /// </summary>
        internal static string Latin {
            get {
                return ResourceManager.GetString("Latin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Matin.
        /// </summary>
        internal static string Message {
            get {
                return ResourceManager.GetString("Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Blok sany.
        /// </summary>
        internal static string Numbers_of_blocks {
            get {
                return ResourceManager.GetString("Numbers of blocks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Operasiany orynday yaqyty.
        /// </summary>
        internal static string Operation_execution_time {
            get {
                return ResourceManager.GetString("Operation execution time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ashyq matin (HEX).
        /// </summary>
        internal static string Plain_Text__HEX_ {
            get {
                return ResourceManager.GetString("Plain Text (HEX)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Kezdeisoq kilt.
        /// </summary>
        internal static string Random_Key {
            get {
                return ResourceManager.GetString("Random Key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Iterasialyq kiltter.
        /// </summary>
        internal static string Round_Keys {
            get {
                return ResourceManager.GetString("Round Keys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на B.
        /// </summary>
        internal static string S {
            get {
                return ResourceManager.GetString("S", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Faildy tandanyz.
        /// </summary>
        internal static string Select_a_file {
            get {
                return ResourceManager.GetString("Select a file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Baptaular.
        /// </summary>
        internal static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Takt.
        /// </summary>
        internal static string Tact {
            get {
                return ResourceManager.GetString("Tact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на File deshifrlendi zhane osy zherde saktaldy.
        /// </summary>
        internal static string The_file_is_decrypted_and_saved_here {
            get {
                return ResourceManager.GetString("The file is decrypted and saved here", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на File shifrlendi zhane osy zherde saktaldy.
        /// </summary>
        internal static string The_file_is_encrypted_and_saved_here {
            get {
                return ResourceManager.GetString("The file is encrypted and saved here", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Kilt 256 bit boluy qajet.
        /// </summary>
        internal static string The_key_must_be_256_bits {
            get {
                return ResourceManager.GetString("The key must be 256 bits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Desifrlenetin habarlama.
        /// </summary>
        internal static string The_message_that_needs_to_be_decrypted {
            get {
                return ResourceManager.GetString("The message that needs to be decrypted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Sifrlenetin habarlama.
        /// </summary>
        internal static string The_message_that_needs_to_be_encrypted {
            get {
                return ResourceManager.GetString("The message that needs to be encrypted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Natije osynda korsetiledi.
        /// </summary>
        internal static string The_result_is_displayed_here {
            get {
                return ResourceManager.GetString("The result is displayed here", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Deshifrlay operasıasynyn oryndaly yaqyty.
        /// </summary>
        internal static string The_time_of_the_decryption_operation {
            get {
                return ResourceManager.GetString("The time of the decryption operation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Sifrleu operasıasynyn oryndaly yaqyty.
        /// </summary>
        internal static string The_time_of_the_encryption_operation {
            get {
                return ResourceManager.GetString("The time of the encryption operation", resourceCulture);
            }
        }
    }
}
